# ========================
# Server
# ========================
server.port=8080

# ========================
# MySQL Database
# ========================
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/delivery_optimizer_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
=======
spring.datasource.url=jdbc:mysql://mysql:3306/delivery_db
>>>>>>> master
spring.datasource.username=root
spring.datasource.password=Csmt457001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================
# JPA / Hibernate
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========================
# JWT
# ========================
app.jwt.secret=ZGVsaXZlcnlvcHRpbWl6ZXJzZWNyZXRrZXkxMjM0NTY3ODkwYWJjZGVmZ2hpams=
app.jwt.expiration-ms=86400000

# ========================
# App
# ========================
spring.application.name=delivery-optimizer
